# Default values for gitops-lab-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2

image:
  repository: iaguilera640/gitops-lab
  tag: "1.0.15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    metallb.universe.tf/address-pool: Default
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: gitops-lab.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}